version: '3.8'

services:
  bot:
    image: tabisch/discordmusicbot:latest
    environment:
      TOKEN: 0
      OWNER: 0
      # PREFIX: "!!"
      # GAME: "Default"
      # STATUS: "ONLINE"
      # SONGINSTATUS: false
      # ALTPREFIX: "NONE"
      # SUCCESS: "ðŸŽ¶"
      # WARNING: "ðŸ’¡"
      # ERROR: "ðŸš«"
      # LOADING: "âŒš"
      # SEARCHING: "ðŸ”Ž"
      # HELP: "help"
      # NPIMAGES: false
      # STAYINCHANNEL: false
      # MAXTIME: 0
      # ALONETIMEUNTILSTOP: 0
      # PLAYLISTSFOLDER: "Playlists"
      # UPDATEALERTS: true
      # LYRICS_DEFAULT: "A-Z Lyrics"
